//@ sourceMappingURL=pages.map
// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(request, responce) {
    return responce.render('index', {
      title: 'Растения из питомника «Садовые самоцветы»'
    });
  };

  exports.faq = function(request, responce) {
    return responce.render('faq', {
      title: 'Частые вопросы'
    });
  };

  exports.articles = function(request, responce) {
    return responce.render('articles', {
      title: 'Статьи'
    });
  };

  exports.about = function(request, responce) {
    return responce.render('about', {
      title: 'О питомнике'
    });
  };

  exports.admin = function(request, responce) {
    return responce.render('admin', {
      title: 'Админка'
    });
  };

}).call(this);
